### ISSUE TITLE
Change password does not show error messages when bad request

### ISSUE THREAD

**Issue by nistala** [crowdresearch/crowdsource-platform#438] opened 2015-08-28 02:45 UTC
Error reporting broken for change password.
Steps to replicate:

Enter incorrect old password
enter new password
enter matching new password 2

submit

**Comment by dmorina** [comment] 2015-08-28 05:06
![screen shot 2015-08-28 at 07 05 47](https://cloud.githubusercontent.com/assets/2858281/9539551/457cbb32-4d53-11e5-804a-4132f599ba98.png)

**Comment by dmorina** [comment] 2015-08-28 05:08
are you sure about this one?
cannot reproduce

**Comment by neilthemathguy** [comment] 2015-08-28 05:49
Looks good to me. Can someone confirm.

**Comment by aginzberg** [comment] 2015-08-28 05:50
yes works for me.

**Comment by aginzberg** [comment] 2015-08-28 17:10
can we close this?

**Comment by dmorina** [comment] 2015-08-28 17:11
I think so

**Comment by neilthemathguy** [comment] 2015-08-28 17:11
lgtm++ @nistala are you still facing this issue?

**Comment by nistala** [comment] 2015-08-28 18:52
try a smaller password

**Comment by nistala** [comment] 2015-08-28 18:53
![screenshot from 2015-08-28 11 52 32](https://cloud.githubusercontent.com/assets/4357428/9554542/64abe6c2-4d7b-11e5-9d03-fb22ffbc598c.png)

**Comment by aginzberg** [comment] 2015-08-28 18:55
good catch

**Comment by dmorina** [comment] 2015-08-29 11:39
resolved

**Closed by dmorina** 2015-08-29 11:39 UTC
Labels: 0. Bug & Critical Issue, MS
