### ISSUE TITLE
Projects with same name club the hits available together (even deleted project)

### ISSUE THREAD

**Issue by shirishgoyal** [crowdresearch/crowdsource-platform#795] opened 2016-09-01 22:04 UTC
![screenshot-workersandbox mturk com 2016-09-01 15-02-52](https://cloud.githubusercontent.com/assets/315012/18186022/3bcebdee-7055-11e6-8a87-568427fbfd7c.png)

Two projects were launched with above name 30 tasks with 3 workers.
One of them was deleted and hits available shows as 60 instead of 30.

**Comment by dmorina** [comment] 2016-09-01 22:05
duplicate of #794 ?

**Comment by shirishgoyal** [comment] 2016-09-01 22:06
I don't think so

**Comment by shirishgoyal** [comment] 2016-09-01 22:06
It should show up as two separate entries even if one project was not deleted.

**Comment by mbernst** [comment] 2016-09-01 22:07
If you launch a HIT with all the same parameters, AMT groups them. This is
a good thing in my opinion.

**Comment by dmorina** [comment] 2016-09-01 22:07
that's how AMT groups them

**Comment by shirishgoyal** [comment] 2016-09-01 22:13
![screenshot-workersandbox mturk com 2016-09-01 15-12-52](https://cloud.githubusercontent.com/assets/315012/18186228/9740f7e0-7056-11e6-91a6-ff888451a9d3.png)

Why will these two show as different entries then?

**Comment by mbernst** [comment] 2016-09-01 22:15
Detailed description might be different? Or maybe one of the titles has
whitespace at the end?

**Comment by shirishgoyal** [comment] 2016-09-01 22:16
Another issue: Since tasks were pushed to AMT on different dates, so HIT Expiration date should have been different in our case.

**Comment by mbernst** [comment] 2016-09-01 23:34
I don't think that matters. If that mattered, all HITs would be different
listings, because they all have slightly different expirations. I assume
they only display the earliest or latest expiration.

**Comment by dmorina** [comment] 2016-09-01 23:42
http://giphy.com/gifs/11clOWGCHzWG7C

**Comment by dmorina** [comment] 2016-09-01 23:51
closing as it's something done by AMT

**Closed by dmorina** 2016-09-01 23:51 UTC
