### ISSUE TITLE
Drop-down menu for blocking workers changes typed in results

### ISSUE THREAD

**Issue by qwertyone** [crowdresearch/crowdsource-platform#765] opened 2016-08-17 17:27 UTC
![image](https://cloud.githubusercontent.com/assets/6076358/17746363/06632466-64b0-11e6-82dc-19e5f1c08c88.png)

When the mouse scrolls down to the second from the top item, it changes to "<" after click.

![image](https://cloud.githubusercontent.com/assets/6076358/17746408/354e64f2-64b0-11e6-8a77-2858f80f2dc8.png)

This might not be a concern after the database is populated.

If possible, it might be useful to limit the menu displayed to the top 4 returned results to minimize the scroll bar drop-down menu within scroll bar window.

**Comment by dmorina** [comment] 2016-08-22 20:12
not able to reproduce

**Comment by shirishgoyal** [comment] 2016-08-23 20:04
Closing as not reproducible

**Closed by shirishgoyal** 2016-08-23 20:04 UTC
