### ISSUE TITLE
Material Design Dropdown Menu Repair

### ISSUE THREAD

**Issue by markwhiting** [crowdresearch/crowdsource-platform#691] opened 2016-05-13 12:42 UTC
The material design dropdown menus are not working consistently and sometimes occlude responses. This happens in several pages of the interface including in tasks and in the authoring window, and perhaps others.

Using a default widget that has been styled might be a solution.

**Comment by shirishgoyal** [comment] 2016-08-23 22:07
Duplicate of #762

**Closed by shirishgoyal** 2016-08-23 22:07 UTC
Labels: bug
